INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:10000
 * Running on http://192.168.0.4:10000
INFO:werkzeug:[33mPress CTRL+C to quit[0m
INFO:service:None
INFO:service:('90bb4baa-cc04-4d14-8bca-50ea950345e8',)
INFO:werkzeug:192.168.0.1 - - [09/Dec/2023 06:13:55] "POST /login HTTP/1.1" 200 -
INFO:service:('90bb4baa-cc04-4d14-8bca-50ea950345e8',)
INFO:service:WTF???
INFO:service:('90bb4baa-cc04-4d14-8bca-50ea950345e8',)
INFO:service:('90bb4baa-cc04-4d14-8bca-50ea950345e8',)
INFO:service:salt_90bb4baa-cc04-4d14-8bca-50ea950345e8
INFO:service:z0DEdhGCuOh6MuVy
INFO:service:z0DEdhGCuOh6MuVy
INFO:werkzeug:192.168.0.1 - - [09/Dec/2023 06:13:58] "GET /confirm HTTP/1.1" 200 -
INFO:service:0
INFO:service:<Request 'http://localhost:10000/profile' [GET]>
INFO:service:eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1dWlkIjoiOTBiYjRiYWEtY2MwNC00ZDE0LThiY2EtNTBlYTk1MDM0NWU4In0.vOJjsU8gjM6hUndvQVoh0NITRLGlSfpxWYGlF8Mz0GA
INFO:service:90bb4baa-cc04-4d14-8bca-50ea950345e8
INFO:service:z0DEdhGCuOh6MuVy
INFO:service:90bb4baa-cc04-4d14-8bca-50ea950345e8
INFO:service:90bb4baa-cc04-4d14-8bca-50ea950345e8
ERROR:mainloop:Exception on /profile [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/app/src/mainloop.py", line 56, in wrapper
    return func(uuid)
  File "/app/src/mainloop.py", line 89, in ProfileHandler
    return Profile(uuid)
  File "/app/src/handlers/profile.py", line 27, in Profile
    if row is not None:
UnboundLocalError: local variable 'row' referenced before assignment
INFO:werkzeug:192.168.0.1 - - [09/Dec/2023 06:14:07] "[35m[1mGET /profile HTTP/1.1[0m" 500 -
