INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:10000
 * Running on http://172.29.0.4:10000
INFO:werkzeug:[33mPress CTRL+C to quit[0m
INFO:service:None
INFO:service:('63662540-ae24-41a8-b524-bb1373686efd',)
INFO:werkzeug:172.29.0.1 - - [09/Dec/2023 06:09:24] "POST /login HTTP/1.1" 200 -
INFO:service:('63662540-ae24-41a8-b524-bb1373686efd',)
INFO:service:WTF???
INFO:service:('63662540-ae24-41a8-b524-bb1373686efd',)
INFO:service:('63662540-ae24-41a8-b524-bb1373686efd',)
INFO:service:salt_63662540-ae24-41a8-b524-bb1373686efd
INFO:service:Dquh1d8ZHARSgrkn
INFO:service:Dquh1d8ZHARSgrkn
INFO:werkzeug:172.29.0.1 - - [09/Dec/2023 06:09:27] "GET /confirm HTTP/1.1" 200 -
INFO:service:0
INFO:service:<Request 'http://localhost:10000/profile' [GET]>
INFO:service:eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1dWlkIjoiNjM2NjI1NDAtYWUyNC00MWE4LWI1MjQtYmIxMzczNjg2ZWZkIn0.RNm8UThMBwq2Lta8RHVM5E7Us6etsB-kkMHL4TkAVV0
INFO:service:63662540-ae24-41a8-b524-bb1373686efd
INFO:service:Dquh1d8ZHARSgrkn
INFO:service:63662540-ae24-41a8-b524-bb1373686efd
ERROR:mainloop:Exception on /profile [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/app/src/mainloop.py", line 56, in wrapper
    return func(uuid)
  File "/app/src/mainloop.py", line 89, in ProfileHandler
    return Profile(uuid)
  File "/app/src/handlers/profile.py", line 25, in Profile
    user_stat = get_user_stat(uuid)
  File "/app/src/handlers/profile.py", line 16, in get_user_stat
    cur.execute(DB.get_prepared('get_user_stat'), (uuid,))
psycopg2.errors.UndefinedFunction: function sum(boolean) does not exist
LINE 2:     ROUND((SUM(completed) / COUNT(*)) * 100, 2) AS stat,
                   ^
HINT:  No function matches the given name and argument types. You might need to add explicit type casts.

INFO:werkzeug:172.29.0.1 - - [09/Dec/2023 06:09:40] "[35m[1mGET /profile HTTP/1.1[0m" 500 -
